// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRUTp2MuTTSiy0AbylkD2rHhIME5B5dI',
    appId: '1:862458611456:web:488a3036ea4d7ee74315e5',
    messagingSenderId: '862458611456',
    projectId: 'blogs-app-19',
    authDomain: 'blogs-app-19.firebaseapp.com',
    storageBucket: 'blogs-app-19.firebasestorage.app',
    measurementId: 'G-E2BEDC4WT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO0SEdKjy8DtcxtYRS7PP-DkeCXHdqzww',
    appId: '1:862458611456:android:53dffebdef318dff4315e5',
    messagingSenderId: '862458611456',
    projectId: 'blogs-app-19',
    storageBucket: 'blogs-app-19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDueYSPSkBvNLmiEQXWtwzVrs0IKQH_NOY',
    appId: '1:862458611456:ios:7e6e5212477d26884315e5',
    messagingSenderId: '862458611456',
    projectId: 'blogs-app-19',
    storageBucket: 'blogs-app-19.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDueYSPSkBvNLmiEQXWtwzVrs0IKQH_NOY',
    appId: '1:862458611456:ios:7e6e5212477d26884315e5',
    messagingSenderId: '862458611456',
    projectId: 'blogs-app-19',
    storageBucket: 'blogs-app-19.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRUTp2MuTTSiy0AbylkD2rHhIME5B5dI',
    appId: '1:862458611456:web:0b1bfbfc402f23294315e5',
    messagingSenderId: '862458611456',
    projectId: 'blogs-app-19',
    authDomain: 'blogs-app-19.firebaseapp.com',
    storageBucket: 'blogs-app-19.firebasestorage.app',
    measurementId: 'G-XJ5GTSKC3L',
  );
}
